# Generated by Django 3.0.8 on 2020-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='album_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='albums',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='todos',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='album_cover',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='artists_name',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='content',
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todos',
            name='completed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
